### ISSUE TITLE
示例里能否补充完整多个节点的代码用法？

### ISSUE THREAD

**Issue by TimVan1596** [monkeymq/jgossip#2]
注意到示例里仅有单个数据结构的用法，没有整个项目的运行情况。
能否补充含seednode和member的整体多个节点，同步网络的运行代码？
![image](https://user-images.githubusercontent.com/24437254/77293951-558d6e00-6d1e-11ea-8430-002d48faf7dc.png)

**Comment by monkeymq** [comment]
Please read README.
https://github.com/monkeymq/jgossip/blob/master/README.md
