### ISSUE TITLE
udp消息接收被截断

### ISSUE THREAD

**Issue by caojingui** [monkeymq/jgossip#3]
1. 当有大量机器上线之后然后永久下线，在消息同步的过程中会导致消息比较长(包含了down状态的机器)。netty对于udp消息默认大小为2048，导致messageHandler获取到的消息被阶段

    
DatagramSocketOptions options = new DatagramSocketOptions();
        options.setReceiveBufferSize(65535);
        //options.setSendBufferSize(65535);

        socket = Vertx.vertx().createDatagramSocket(options);

**Comment by monkeymq** [comment]
You are right ,will improve it ASAP
